{% set name = "zope.component" %}
{% set version = "6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zope_component-{{ version }}.tar.gz
  sha256: 79b807f29d82576e59d82187239549d5715759ab797b60a5bd69cc36e0449c09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - zope.event
    - zope.hookable >=4.2.0
    - zope.interface >=5.3

test:
  imports:
    - zope
    - zope.component
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zopefoundation/zope.component
  summary: Zope Component Architecture
  license: ZPL-2.1 AND BSD-3-Clause
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
