{% set name = "zope.component" %}
{% set version = "6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zope.component-{{ version }}.tar.gz
  sha256: 9a0a0472ad201b94b4fe6741ce9ac2c30b8bb22c516077bf03692dec4dfb6906

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - setuptools
    - zope.event
    - zope.hookable >=4.2.0
    - zope.interface >=5.3

test:
  imports:
    - zope
    - zope.component
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/zope.component
  summary: Zope Component Architecture
  license: ZPL-2.1 & BSD-3-Clause
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
